name: Build the react js project 
on: [push, pull_request]
jobs:
 Build:
  runs-on : ubuntu-latest
  steps: 
    - name: Get checkout
    - uses: actions/checkout@v3
    - name: Install node js 
    - uses: actions/setup-node@v3
      with:
         node-version: 18
    - run: npm ci
    - run: npm test       
 Deoply:
  runs-on : ubuntu-latest
  steps: 
    - name: Get checkout
    - uses: actions/checkout@v3
    - name: Install node js 
    - uses: actions/setup-node@v3
      with:
         node-version: 18
    - run: npm ci
    - run: npm build test 
    - name: Deoplyment 
    - run: echo "deoplyment..."
    
  
