name: Git action react js
on:
  pull_request:
  
    type:
      - opened
      - edited
      - review_request_removed 
      - closed
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
  deoply: 
   needs: test 
   runs-on: ubuntu-latest
   steps:
      - name: Print contents of the workspace directory
        run: ls $GITHUB_WORKSPACE



  
